# Generated by Django 3.2.9 on 2021-11-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_sponsoredjobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
